### ISSUE TITLE
GPT3.5/4评测相关

### ISSUE THREAD

**Issue by yucc-leon** [twang2218/model-vocab-check#2]
按照本项目的评测结果，GPT4/3.5仅支持500+中文字符，跟用户感知的偏差是不是有点大了，还是说最常用的汉字真就这么几百个？

**Comment by twang2218** [comment]
项目分析的是tokenizer中的vocab的内容，在vocab里，确实就这么几百个汉字。

不过，GPT使用的是[BBPE(byte-level Byte-Pair-Encoding)](https://huggingface.co/docs/transformers/main/tokenizer_summary#bytepair-encoding-bpe)，也就是说，除了这几百个汉字外，vocab里面还有每个字节0x00-0xFF这256种形式的字节词，而每一个汉字在UTF8编码后，会形成3-4字节数据，因此理论上BBPE是可以支持所有汉字组合的。

但是，就和一个英文单词一般尽量对应1-2个token而不是每个字母对应1个token一样，中文词汇甚至中文汉字被拆分成多个token，会伤害模型对于语言的理解能力。这个问题在 Chinese-LLaMA-Alpaca 项目中也有过[讨论](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#%E9%97%AE%E9%A2%984%E4%B8%BA%E4%BB%80%E4%B9%88%E8%A6%81%E6%89%A9%E5%85%85%E8%AF%8D%E8%A1%A8%E7%9B%B4%E6%8E%A5%E5%9C%A8%E5%8E%9F%E7%89%88llama%E4%B8%8A%E7%94%A8%E4%B8%AD%E6%96%87%E9%A2%84%E8%AE%AD%E7%BB%83%E4%B8%8D%E8%A1%8C%E5%90%97)。

所以在识字率部分，一个汉字被拆分为多个token的，不计入计数，在图上则通过变浅的方式来反应该汉字的并非单一token。

<img width="709" alt="截屏2023-07-06 下午4 09 38" src="https://github.com/twang2218/vocab-coverage/assets/6299096/079d1669-5ba7-4509-90e5-4b4bb623c882">


此外，理论上支持识别所有汉字，不等于事实上可以理解所有汉字，因为要理解对应汉字，就必须让词向量空间对汉字的语义处于对应的位置。

在这个项目里，由于我们需要对比词向量在输入端和输出端的差异变化，因此，我们仅使用模型tokenizer的词表vocab里所含的字词进行计算，因此超出词表的词，将无法取得输入端的input embedding的token embedding。所以，绘制GPT输入输出端embedding分布图的时候，也只能包含词表里这几百个字了。

还有一个需要考虑的问题是，这里主要看的是输入端的词向量，而模型对文字的理解不止在输入端，而是整个模型都在理解，因此如果模型足够先进，勤能补拙，可以在后面的Tranformer层中学到被拆成碎片的汉字的含义。对于GPT这种超大规模语言模型来说，一个汉字被拆成碎片造成的伤害，可以在后期进行弥补，而最终呈现到用户前的，已经是最后的结果了，这种伤害就不容易凸显。

大语言模型是个复杂的东西，不能一言以蔽之。这个项目是从一个角度去看大语言模型，特别是对中文的支持情况，但这不能够作为最终给大语言模型的判定，只能作为一个角度的参考。

**Comment by yucc-leon** [comment]
感谢回复，非常详尽的介绍，受教了
